### ISSUE TITLE
Using internal version of `meta.ListOptions` avoids parsing of selector

### ISSUE THREAD

**Issue by Iceber** [clusterpedia-io/client-go#2]
https://github.com/clusterpedia-io/client-go/blob/3b51fbff9f2b90fda7c33de88f22a773083a7934/tools/builder/options.go#L45-L58

The `LabelSelector` of `metav1.ListOptions` is in string format, and each time a new selector is added, the labelSelector needs to be parsed.
If you use [`metainternal.ListOpitons`](https://github.com/kubernetes/kubernetes/blob/2af53e9f64eee81a09fd0fd1f0fc96ce0859eb0f/staging/src/k8s.io/apimachinery/pkg/apis/meta/internalversion/types.go#L29) directly, you can avoid parsing each time by simply converting to `metav1.ListOptions` when calling `Options()`

```go
type listOptionBuilder metainternal.ListOptions
```

**Comment by calvin0327** [comment]
That's true. The `metainternal.ListOpitons` can  avoid parsing each time.

/assign
