### ISSUE TITLE
remove fake-apiserver to repo `clusterpedia-io/fake-apiserver`

### ISSUE THREAD

**Issue by calvin0327** [clusterpedia-io/client-go#41]
`fake-apiserver` references `kubernetes. io` pkg cause users need to replace all of kubenetes's pkgs if they want to use client-go. this was very unfriendly and after discussion, we are now going to separate the fake-apiserver to  repo `clusterpedia-io/fake-apiserver` to keep client-go lightweight.

- [x] pull fake-apiserver to `clusterpedia-io/fake-apiserver`
- [x] init `clusterpedia-io/fake-apiserver`
- [x] remove client-go/fake-apiserver and update go.mod

**Comment by calvin0327** [comment]
fake-apiserver had be removed to repo: https://github.com/clusterpedia-io/fake-apiserver

**Comment by Iceber** [comment]
pkg/version  seems to be used only by fake-apiserver

**Comment by Iceber** [comment]
The fake-apiserver repo should use its own mod
eg.
https://github.com/clusterpedia-io/fake-apiserver/blob/ddafdbaf08f6c3b11576f41aad3df9cd21487ffc/kubeapiserver/apiserver.go#L17

**Comment by liangyongzhenya** [comment]
ok，I have a try.

**Comment by calvin0327** [comment]
The task had completed, I will close the issue.
